#!/usr/bin/env bash
#
# Stamp the release version from ./VERSION into every schema $id URL and the
# documentation references that point at them. Idempotent: re-running replaces
# any existing version segment, so it also serves as the CI drift check via
# `git diff --exit-code`.
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VERSION="$(tr -d '[:space:]' < VERSION)"
if [[ -z "$VERSION" ]]; then
    echo "VERSION file is empty" >&2
    exit 1
fi

# Files whose smpte.github.io/st2138-a/.../interface/schema/ URLs carry the
# version path segment. device.json is generated by build-openapi.sh and
# inherits the stamped $id from device.yaml, so it is not listed here.
files=(
    interface/schema/device.yaml
    interface/schema/client-hints.yaml
    docs/schema_validation.md
)

# Insert (first run) or replace (later runs) the <version> segment sitting
# between st2138-a/ and interface/schema/. The optional ([^/]+/) group is the
# existing version, if any; all other URLs (e.g. OpenAPI servers) are untouched.
for f in "${files[@]}"; do
    sed -E -i \
        "s#(smpte\.github\.io/st2138-a/)([^/]+/)?interface/schema/#\1${VERSION}/interface/schema/#g" \
        "$f"
done

# OpenAPI info.version — the sole version: key in the root spec. The bundled
# docs/openapi.yaml inherits this value when build-openapi.sh runs.
sed -E -i \
    "s#^([[:space:]]*version:[[:space:]]*).*#\1'${VERSION}'#" \
    interface/openapi/openapi.yaml

echo "Stamped version '${VERSION}' into:"
printf '  %s\n' "${files[@]}" interface/openapi/openapi.yaml
echo "Run ./build-openapi.sh to regenerate device.json and docs/openapi.yaml with the stamped version."
