openapi: 3.1.0
info:
  title: Catena API
  version: '1.0'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
servers:
  - url: https://device.catenamedia.tv:443/st2138-api/v1
security:
  - oauth2:
      - st2138:op
  - oauth2:
      - st2138:cfg
  - oauth2:
      - st2138:adm
  - oauth2:
      - st2138:mon
paths:
  /health:
    get:
      summary: Checks the health of a Catena REST service
      operationId: Health
      tags:
        - Discovery
  /devices:
    get:
      summary: Gets a list of slot numbers that are occupied by a device
      description: Retrieves a list of slot numbers that are occupied by a device.
      operationId: Devices
      tags:
        - Discovery
  /{slot}:
    get:
      summary: Gets a device model with a single request. Note that device models can be very large, and so clients should consider using the streaming endpoint instead.
      operationId: DeviceRequest
      tags:
        - Discovery
  /{slot}/stream:
    get:
      summary: Gets a device model with as a stream of stringified DeviceComponents.
      operationId: DeviceStreamRequest
      tags:
        - Discovery
  /{slot}/command/{fqoid}:
    post:
      summary: Execute a command on a device model
      operationId: ExecuteCommand
      security:
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:mon:w
      tags:
        - Commands
  /{slot}/command/{fqoid}/stream:
    post:
      summary: Execute a command on a device model
      operationId: ExecuteCommandStream
      security:
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:mon:w
      tags:
        - Commands
  /{slot}/asset/{fqoid}:
    get:
      summary: get an asset without streaming
      operationId: GetAsset
      tags:
        - Assets
    post:
      summary: load an asset
      operationId: LoadAsset
      security:
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
      tags:
        - Assets
    put:
      summary: Overwrite an asset
      operationId: OverwriteAsset
      security:
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
      tags:
        - Assets
    delete:
      summary: Delete an asset
      operationId: DeleteAsset
      security:
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
      tags:
        - Assets
  /{slot}/asset/{fqoid}/stream:
    get:
      summary: get an asset, or a stream of assets from the device
      operationId: AssetStream
      tags:
        - Assets
  /{slot}/param-info/{fqoid}:
    get:
      summary: "Gets information about a parameter within a device model. \nBecause this is a unary request, recursive queries are not supported.\n"
      operationId: ParamInfo
      tags:
        - Parameters
        - Subscriptions
  /{slot}/param-info/{fqoid}/stream:
    get:
      summary: Gets information about parameters within a device model
      operationId: ParamInfoStream
      tags:
        - Parameters
        - Subscriptions
  /{slot}/param-info/stream:
    get:
      summary: Gets information about all top-level parameters within a device model
      operationId: TopLevelParamInfoStream
      tags:
        - Parameters
        - Subscriptions
  /{slot}/value/{fqoid}:
    get:
      summary: Get a parameter's value
      operationId: GetValue
      tags:
        - Parameters
    put:
      summary: Set a parameter's value
      operationId: SetValue
      security:
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:mon:w
      tags:
        - Parameters
  /{slot}/values:
    put:
      summary: Sets the values of multiple parameters idempotently - i.e. either all are set or none are
      operationId: SetValues
      security:
        - oauth2:
            - st2138:op:w
        - oauth2:
            - st2138:cfg:w
        - oauth2:
            - st2138:adm:w
        - oauth2:
            - st2138:mon:w
      tags:
        - Parameters
  /{slot}/subscriptions:
    get:
      summary: Get the current subscriptions
      operationId: GetSubscriptions
      tags:
        - Subscriptions
        - Parameters
    put:
      summary: Set the current subscriptions
      operationId: SetSubscriptions
      tags:
        - Parameters
        - Subscriptions
  /{slot}/subscriptions/stream:
    get:
      summary: Get a stream of the current subscriptions
      operationId: GetSubscriptionsStream
      tags:
        - Subscriptions
        - Parameters
  /{slot}/param/{fqoid}:
    get:
      summary: Retrieves a parameter descriptor from the device model.
      operationId: Param
      tags:
        - Parameters
  /connect:
    get:
      summary: Connects a client to a service for updates on value changes.
      operationId: Connect
      tags:
        - Updates
  /{slot}/language-pack/{language-code}:
    get:
      summary: Get a language pack
      operationId: GetLanguagePack
      tags:
        - Languages
    post:
      summary: "Add a new language pack to the device model. \nAttempts to overwrite an existing language pack will fail with 403 Forbidden.\n"
      operationId: AddLanguagePack
      security:
        - oauth2:
            - st2138:adm:w
      tags:
        - Languages
    delete:
      summary: |
        Delete a language pack from the device model.
        Only packs that are field upgrades can be deleted.
        Attempts to delete a pack that was shipped with the device will fail with 403 Forbidden.
      operationId: DeleteLanguagePack
      security:
        - oauth2:
            - st2138:adm:w
      tags:
        - Languages
    put:
      summary: "Update a language pack in the device model.\nAttempts to update a pack that was shipped with the device will fail with 403 Forbidden.\nOnly packs that are field upgrades can be updated.  \n"
      operationId: UpdateLanguagePack
      security:
        - oauth2:
            - st2138:adm:w
      tags:
        - Languages
  /{slot}/languages:
    get:
      summary: Gets a list of language codes that are supported by the device model
      operationId: Languages
      security:
        - oauth2:
            - st2138:op
        - oauth2:
            - st2138:cfg
        - oauth2:
            - st2138:mon
        - oauth2:
            - st2138:adm
      tags:
        - Languages
  /access:
    get:
      summary: Refresh the access token
      operationId: RefreshToken
      tags:
        - Access Management
    post:
      summary: Revoke access for a subject
      operationId: RevokeAccess
      security:
        - oauth2:
            - st2138:adm:w
      tags:
        - Access Management
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://device.catenamedia.tv/api/v1/oauth2/token
          scopes:
            st2138:op: Read only access to operate a device
            st2138:op:w: Read and write access to operate a device
            st2138:cfg: Read only access to configure a device
            st2138:cfg:w: Read and write access to configure a device
            st2138:adm: Read only access to administer a device
            st2138:adm:w: Read and write access to administer a device
            st2138:mon: Read only access to monitor a device
            st2138:mon:w: Read and write access to monitor a device